version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - "8080:8080"
    networks:
      - mynetworkdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/employeedb?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - mysqldb

  mysqldb:
    container_name: mysqldb
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    networks:
      - mynetworkdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employeedb
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

networks:
  mynetworkdb:
